name: Deploy to GitHub Pages
on:
  push:
    branches: ["master"] # or "main" depending on your branch name
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/actions-conduit-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './artifacts' # This tells GitHub to use your folder!
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4